$(document).ready(function()
{
	$('#Portfolio').ready(function()
	{
		$('#list').ready(function()
		{
			$('li').hover(function()
			{
				$(this).toggleClass('showDescription');
			});
		});
	});
});
